# PORTARIA  No  42,  DE  14 DE  ABRIL  DE 1999 (ATUALIZADA) (*)
# (Publicada no D.O.U. de 15.04.99)

library(magrittr)
library(ggplot2)

municipios <- geobr::read_municipality()

dados <- readr::read_csv2(
  file = './dados/despesas_municipais_2022_funcao.csv')

espelho <- dados %>%
  dplyr::rename('subfuncao' = conta_bd) %>%
  dplyr::mutate(funcao = dplyr::case_when(
    subfuncao == 'Ação Legislativa' ~ 'Legislativa',
    subfuncao == 'Controle Externo' ~ 'Legislativa',
    subfuncao == 'Ação Judiciária' ~ 'Judiciária',
    subfuncao == 'Defesa do Interesse Público no Processo Judiciário' ~ 'Judiciária',
    subfuncao == 'Defesa da Ordem Jurídica' ~ 'Essencial à Justiça',
    subfuncao == 'Representação Judicial e Extrajudicial' ~ 'Essencial à Justiça',
    subfuncao == 'Planejamento e Orçamento' ~ 'Administração',
    subfuncao == 'Administração Geral' ~ 'Administração',
    subfuncao == 'Administração Financeira' ~ 'Administração',
    subfuncao == 'Controle Interno' ~ 'Administração',
    subfuncao == 'Normatização e Fiscalização' ~ 'Administração',
    subfuncao == 'Tecnologia da Informação' ~ 'Administração',
    subfuncao == 'Ordenamento Territorial' ~ 'Administração',
    subfuncao == 'Formação de Recursos Humanos' ~ 'Administração',
    subfuncao == 'Administração de Receitas' ~ 'Administração',
    subfuncao == 'Administração de Concessões' ~ 'Administração',
    subfuncao == 'Comunicação Social' ~ 'Administração',
    subfuncao == 'Defesa Aérea' ~ 'Defesa Nacional',
    subfuncao == 'Defesa Áerea' ~ 'Defesa Nacional',
    subfuncao == 'Defesa Naval' ~ 'Defesa Nacional',
    subfuncao == 'Defesa Terrestre' ~ 'Defesa Nacional',
    subfuncao == 'Policiamento' ~ 'Segurança Pública',
    subfuncao == 'Defesa Civil' ~ 'Segurança Pública',
    subfuncao == 'Informação e Inteligência' ~ 'Segurança Pública',
    subfuncao == 'Relações Diplomáticas' ~ 'Relações Exteriores',
    subfuncao == 'Cooperação Internacional' ~ 'Relações Exteriores',
    subfuncao == 'Assistência ao Idoso' ~ 'Assistência Social',
    subfuncao == 'Assistência ao Portador de Deficiência' ~ 'Assistência Social',
    subfuncao == 'Assistência à Criança e ao Adolescente' ~ 'Assistência Social',
    subfuncao == 'Assistência Comunitária' ~ 'Assistência Social',
    subfuncao == 'Previdência Básica' ~ 'Previdência Social',
    subfuncao == 'Previdência do Regime Estatutário' ~ 'Previdência Social',
    subfuncao == 'Previdência Complementar' ~ 'Previdência Social',
    subfuncao == 'Previdência Especial' ~ 'Previdência Social',
    subfuncao == 'Atenção Básica' ~ 'Saúde',
    subfuncao == 'Assistência Hospitalar e Ambulatorial' ~ 'Saúde',
    subfuncao == 'Suporte Profilático e Terapêutico' ~ 'Saúde',
    subfuncao == 'Vigilância Sanitária' ~ 'Saúde',
    subfuncao == 'Vigilância Epidemiológica' ~ 'Saúde',
    subfuncao == 'Alimentação e Nutrição' ~ 'Saúde',
    subfuncao == 'Proteção e Benefícios ao Trabalhador' ~ 'Trabalho',
    subfuncao == 'Relações de Trabalho' ~ 'Trabalho',
    subfuncao == 'Empregabilidade' ~ 'Trabalho',
    subfuncao == 'Fomento ao Trabalho' ~ 'Trabalho',
    subfuncao == 'Ensino Fundamental' ~ 'Educação',
    subfuncao == 'Ensino Médio' ~ 'Educação',
    subfuncao == 'Ensino Profissional' ~ 'Educação',
    subfuncao == 'Ensino Superior' ~ 'Educação',
    subfuncao == 'Educação Infantil' ~ 'Educação',
    subfuncao == 'Educação de Jovens e Adultos' ~ 'Educação',
    subfuncao == 'Educação Especial' ~ 'Educação',
    subfuncao == 'Educação Básica' ~ 'Educação',
    subfuncao == 'Patrimônio Histórico, Artístico e Arqueológico' ~ 'Cultura',
    subfuncao == 'Difusão Cultural' ~ 'Cultura',
    subfuncao == 'Custódia e Reintegração Social' ~ 'Direitos da Cidadania',
    subfuncao == 'Direitos Individuais, Coletivos e Difusos' ~ 'Direitos da Cidadania',
    subfuncao == 'Assistência aos Povos Indígenas' ~ 'Direitos da Cidadania',
    subfuncao == 'Infra-Estrutura Urbana' ~ 'Urbanismo',
    subfuncao == 'Infraestrutura Urbana' ~ 'Urbanismo',
    subfuncao == 'Serviços Urbanos' ~ 'Urbanismo',
    subfuncao == 'Transportes Coletivos Urbanos' ~ 'Urbanismo',
    subfuncao == 'Habitação Rural' ~ 'Habitação',
    subfuncao == 'Habitação Urbana' ~ 'Habitação',
    subfuncao == 'Saneamento Básico Rural' ~ 'Saneamento',
    subfuncao == 'Saneamento Básico Urbano' ~ 'Saneamento',
    subfuncao == 'Preservação e Conservação Ambiental' ~ 'Gestão Ambiental',
    subfuncao == 'Controle Ambiental' ~ 'Gestão Ambiental',
    subfuncao == 'Recuperação de Áreas Degradadas' ~ 'Gestão Ambiental',
    subfuncao == 'Recursos Hídricos' ~ 'Gestão Ambiental',
    subfuncao == 'Meteorologia' ~ 'Gestão Ambiental',
    subfuncao == 'Desenvolvimento Científico' ~ 'Ciência e Tecnologia',
    subfuncao == 'Desenvolvimento Tecnológico e Engenharia' ~ 'Ciência e Tecnologia',
    subfuncao == 'Difusão do Conhecimento Científico e Tecnológico' ~ 'Ciência e Tecnologia',
    subfuncao == 'Promoção da Produção Vegetal' ~ 'Agricultura',
    subfuncao == 'Promoção da Produção Animal' ~ 'Agricultura',
    subfuncao == 'Defesa Sanitária Vegetal' ~ 'Agricultura',
    subfuncao == 'Defesa Sanitária Animal' ~ 'Agricultura',
    subfuncao == 'Abastecimento' ~ 'Agricultura',
    subfuncao == 'Extensão Rural' ~ 'Agricultura',
    subfuncao == 'Irrigação' ~ 'Agricultura',
    subfuncao == 'Promoção da Produção Agropecuária' ~ 'Agricultura',
    subfuncao == 'Defesa Agropecuária' ~ 'Agricultura',
    subfuncao == 'Reforma Agrária' ~ 'Organização Agrária',
    subfuncao == 'Colonização' ~ 'Organização Agrária',
    subfuncao == 'Promoção Industrial' ~ 'Indústria',
    subfuncao == 'Produção Industrial' ~ 'Indústria',
    subfuncao == 'Mineração' ~ 'Indústria',
    subfuncao == 'Propriedade Industrial' ~ 'Indústria',
    subfuncao == 'Normalização e Qualidade' ~ 'Indústria',
    subfuncao == 'Promoção Comercial' ~ 'Comércio e Serviços',
    subfuncao == 'Comercialização' ~ 'Comércio e Serviços',
    subfuncao == 'Comércio Exterior' ~ 'Comércio e Serviços',
    subfuncao == 'Serviços Financeiros' ~ 'Comércio e Serviços',
    subfuncao == 'Turismo' ~ 'Comércio e Serviços',
    subfuncao == 'Comunicações Postais' ~ 'Comunicações',
    subfuncao == 'Telecomunicações' ~ 'Comunicações',
    subfuncao == 'Conservação de Energia' ~ 'Energia',
    subfuncao == 'Energia Elétrica' ~ 'Energia',
    subfuncao == 'Combustíveis Minerais' ~ 'Energia',
    subfuncao == 'Biocombustíveis' ~ 'Energia',
    subfuncao == 'Transporte Aéreo' ~ 'Transporte',
    subfuncao == 'Transporte Rodoviário' ~ 'Transporte',
    subfuncao == 'Transporte Ferroviário' ~ 'Transporte',
    subfuncao == 'Transporte Hidroviário' ~ 'Transporte',
    subfuncao == 'Transportes Especiais' ~ 'Transporte',
    subfuncao == 'Desporto de Rendimento' ~ 'Desporto e Lazer',
    subfuncao == 'Desporto Comunitário' ~ 'Desporto e Lazer',
    subfuncao == 'Lazer' ~ 'Desporto e Lazer',
    subfuncao == 'Refinanciamento da Dívida Interna' ~ 'Encargos Especiais',
    subfuncao == 'Refinanciamento da Dívida Externa' ~ 'Encargos Especiais',
    subfuncao == 'Serviço da Dívida Interna' ~ 'Encargos Especiais',
    subfuncao == 'Serviço da Dívida Externa' ~ 'Encargos Especiais',
    subfuncao == 'Outras Transferências' ~ 'Encargos Especiais',
    subfuncao == 'Outros Encargos Especiais' ~ 'Encargos Especiais',
    subfuncao == 'Transferências para a Educação Básica' ~ 'Encargos Especiais',
    subfuncao == 'Legislativa' ~ 'Legislativa',
    subfuncao == 'Judiciária' ~ 'Judiciária',
    subfuncao == 'Essencial à Justiça' ~ 'Essencial à Justiça',
    subfuncao == 'Administração' ~ 'Administração',
    subfuncao == 'Defesa Nacional' ~ 'Defesa Nacional',
    subfuncao == 'Segurança Pública' ~ 'Segurança Pública',
    subfuncao == 'Relações Exteriores' ~ 'Relações Exteriores',
    subfuncao == 'Assistência Social' ~ 'Assistência Social',
    subfuncao == 'Previdência Social' ~ 'Previdência Social',
    subfuncao == 'Saúde' ~ 'Saúde',
    subfuncao == 'Trabalho' ~ 'Trabalho',
    subfuncao == 'Educação' ~ 'Educação',
    subfuncao == 'Cultura' ~ 'Cultura',
    subfuncao == 'Direitos da Cidadania' ~ 'Direitos da Cidadania',
    subfuncao == 'Urbanismo' ~ 'Urbanismo',
    subfuncao == 'Habitação' ~ 'Habitação',
    subfuncao == 'Saneamento' ~ 'Saneamento',
    subfuncao == 'Gestão Ambiental' ~ 'Gestão Ambiental',
    subfuncao == 'Ciência e Tecnologia' ~ 'Ciência e Tecnologia',
    subfuncao == 'Agricultura' ~ 'Agricultura',
    subfuncao == 'Organização Agrária' ~ 'Organização Agrária',
    subfuncao == 'Indústria' ~ 'Indústria',
    subfuncao == 'Comércio e Serviços' ~ 'Comércio e Serviços',
    subfuncao == 'Comunicações' ~ 'Comunicações',
    subfuncao == 'Energia' ~ 'Energia',
    subfuncao == 'Transporte' ~ 'Transporte',
    subfuncao == 'Desporto e Lazer' ~ 'Desporto e Lazer',
    subfuncao == 'Encargos Especiais' ~ 'Encargos Especiais',
    subfuncao == 'Demais Subfunções Legislativa' ~ 'Legislativa',
    subfuncao == 'Demais Subfunções Judiciária' ~ 'Judiciária',
    subfuncao == 'Demais Subfunções Essencial à Justiça' ~ 'Essencial à Justiça',
    subfuncao == 'Demais Subfunções Administração' ~ 'Administração',
    subfuncao == 'Demais Subfunções Defesa Nacional' ~ 'Defesa Nacional',
    subfuncao == 'Demais Subfunções Segurança Pública' ~ 'Segurança Pública',
    subfuncao == 'Demais Subfunções Relações Exteriores' ~ 'Relações Exteriores',
    subfuncao == 'Demais Subfunções Assistência Social' ~ 'Assistência Social',
    subfuncao == 'Demais Subfunções Previdência Social' ~ 'Previdência Social',
    subfuncao == 'Demais Subfunções Saúde' ~ 'Saúde',
    subfuncao == 'Demais Subfunções Trabalho' ~ 'Trabalho',
    subfuncao == 'Demais Subfunções Educação' ~ 'Educação',
    subfuncao == 'Demais Subfunções Cultura' ~ 'Cultura',
    subfuncao == 'Demais Subfunções Direitos da Cidadania' ~ 'Direitos da Cidadania',
    subfuncao == 'Demais Subfunções Urbanismo' ~ 'Urbanismo',
    subfuncao == 'Demais Subfunções Habitação' ~ 'Habitação',
    subfuncao == 'Demais Subfunções Saneamento' ~ 'Saneamento',
    subfuncao == 'Demais Subfunções Gestão Ambiental' ~ 'Gestão Ambiental',
    subfuncao == 'Demais Subfunções Ciência e Tecnologia' ~ 'Ciência e Tecnologia',
    subfuncao == 'Demais Subfunções Agricultura' ~ 'Agricultura',
    subfuncao == 'Demais Subfunções Organização Agrária' ~ 'Organização Agrária',
    subfuncao == 'Demais Subfunções Indústria' ~ 'Indústria',
    subfuncao == 'Demais Subfunções Comércio e Serviços' ~ 'Comércio e Serviços',
    subfuncao == 'Demais Subfunções Comunicações' ~ 'Comunicações',
    subfuncao == 'Demais Subfunções Energia' ~ 'Energia',
    subfuncao == 'Demais Subfunções Transporte' ~ 'Transporte',
    subfuncao == 'Demais Subfunções Desporto e Lazer' ~ 'Desporto e Lazer',
    subfuncao == 'Demais Subfunções Encargos Especiais' ~ 'Encargos Especiais',
    subfuncao == 'Despesas Exceto Intraorçamentárias' ~ 'Exceto Intraorçamentárias',
    subfuncao == 'Despesas Intraorçamentárias' ~ 'Intraorçamentárias'
  ))

dados_funcao <- espelho %>%
  dplyr::select(id_municipio,
                estagio_bd,
                funcao,
                valor) %>%
  dplyr::group_by(id_municipio,
                  estagio_bd,
                  funcao) %>%
  dplyr::summarise(valor = sum(valor)) %>%
  dplyr::ungroup()

estagio <- 'Despesas Empenhadas'
funcao <- 'Educação'
estado <- 'MG'
legenda <- paste0('Estágio: ', estagio, '\n',
                  'Função: ', funcao, '\n',
                  'Estado: ', estado, '\n')

dados_funcao_filtrado <- dados_funcao %>%
  dplyr::filter(estagio_bd == estagio) %>%
  dplyr::filter(funcao == funcao)

graf_funcao_filtrado <- municipios %>%
  dplyr::left_join(dados_funcao_filtrado,
                   by = c('code_muni' = 'id_municipio')) %>%
  dplyr::filter(abbrev_state == estado) %>%
  ggplot() +
  geom_sf(mapping = aes(fill = as.numeric(valor/1000))) +
  scale_fill_distiller(palette = 'Greens',
                       direction = 1,
                       name = legenda,
                       labels = scales::dollar_format(prefix = 'R$',
                                                      decimal.mark = ',',
                                                      big.mark = '.')) +
  theme_void()

graf_funcao_filtrado

